Description: >
  Patrick Coutinho | Deploy a high-availability web app using CloudFormation | Udacity Cloud DevOps Engineer Nanodegree

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  BucketName:
    Description: Bucket Name
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${BucketName}"

Outputs:
  S3Bucket:
    Description: A reference to the created bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${EnvironmentName}-S3BucketName